### ISSUE TITLE
How to use a proxy to get proxies?

### ISSUE THREAD

**Issue by chsnt** [chill117/proxy-lists#104]
As far as I understand ```ProxyLists.getProxies``` use module [request](https://www.npmjs.com/package/request) for http(s)-requests.
Can i set my options for request? I want to use my proxy for get proxy lists ;3

**Comment by chill117** [comment]
Hello, @chsnt. This is an interesting idea ;) This is a little bit tricky because this module uses both request and puppeteer under-the-hood to scrape web pages. So you will have to configure both of those to use a proxy. Something like this should work:
```js
var ProxyLists = require('proxy-lists');
ProxyLists.getProxies({
	browser: {
		// arguments passed to puppeteer browser instance:
		args: [ '--proxy-server=127.0.0.1:9876' /* your proxy */ ]
	},
	defaultRequestOptions: {
		// Passed as default options to the request module.
		// Read the following for details about proxy usage and request:
		// https://github.com/request/request#proxies
		proxy: 'http://127.0.0.1:9876',
	}
});
```
Replace the proxy strings with your proxy details.
