### ISSUE TITLE
blackhatworld proxies are always filtered

### ISSUE THREAD

**Issue by damdev** [chill117/proxy-lists#60]
Because their proxies don't have `anonymityLevel` nor `protocol`, and they will be filtered because they are not a valid proxy according to https://github.com/chill117/proxy-lists/blob/master/index.js#L321 .

Thanks!

**Comment by chill117** [comment]
So this isn't so clear. The `options` provided to `getProxies()` is used to filter the proxies after received from each source. For the sources that don't have `anonymityLevel` or `protocol`, this is a problem because they will always be filtered away when using the `anonymityLevels` or `protocols` options.

Possible solutions:
* Keep the proxies (don't filter them away) when they are missing `anonymityLevel` or `protocol` even when the `anonymityLevels` or `protocols` options are used. This will be a change to the default behavior of the module.
* Maintain the current behavior, but add a new option that will change the behavior to that described above (e.g `looseFiltering` or some better name).

**Comment by chill117** [comment]
Added new `filterMode` option. Default is `'strict'`, which will maintain the current behavior of the module. Use `filterMode: 'loose'` to include proxies with NULL or missing values.
